// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Sources/corenote/Protobuf/notestore.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct CNNoteStoreProto: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var document: CNDocument {
    get {_document ?? CNDocument()}
    set {_document = newValue}
  }
  /// Returns true if `document` has been explicitly set.
  var hasDocument: Bool {self._document != nil}
  /// Clears the value of `document`. Subsequent reads from it will return its default value.
  mutating func clearDocument() {self._document = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _document: CNDocument? = nil
}

struct CNDocument: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var version: Int32 {
    get {_version ?? 0}
    set {_version = newValue}
  }
  /// Returns true if `version` has been explicitly set.
  var hasVersion: Bool {self._version != nil}
  /// Clears the value of `version`. Subsequent reads from it will return its default value.
  mutating func clearVersion() {self._version = nil}

  var note: CNNote {
    get {_note ?? CNNote()}
    set {_note = newValue}
  }
  /// Returns true if `note` has been explicitly set.
  var hasNote: Bool {self._note != nil}
  /// Clears the value of `note`. Subsequent reads from it will return its default value.
  mutating func clearNote() {self._note = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _version: Int32? = nil
  fileprivate var _note: CNNote? = nil
}

struct CNNote: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var noteText: String {
    get {_noteText ?? String()}
    set {_noteText = newValue}
  }
  /// Returns true if `noteText` has been explicitly set.
  var hasNoteText: Bool {self._noteText != nil}
  /// Clears the value of `noteText`. Subsequent reads from it will return its default value.
  mutating func clearNoteText() {self._noteText = nil}

  var attributeRun: [CNAttributeRun] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _noteText: String? = nil
}

struct CNAttributeRun: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var length: Int32 {
    get {_storage._length ?? 0}
    set {_uniqueStorage()._length = newValue}
  }
  /// Returns true if `length` has been explicitly set.
  var hasLength: Bool {_storage._length != nil}
  /// Clears the value of `length`. Subsequent reads from it will return its default value.
  mutating func clearLength() {_uniqueStorage()._length = nil}

  var paragraphStyle: CNParagraphStyle {
    get {_storage._paragraphStyle ?? CNParagraphStyle()}
    set {_uniqueStorage()._paragraphStyle = newValue}
  }
  /// Returns true if `paragraphStyle` has been explicitly set.
  var hasParagraphStyle: Bool {_storage._paragraphStyle != nil}
  /// Clears the value of `paragraphStyle`. Subsequent reads from it will return its default value.
  mutating func clearParagraphStyle() {_uniqueStorage()._paragraphStyle = nil}

  var font: CNFont {
    get {_storage._font ?? CNFont()}
    set {_uniqueStorage()._font = newValue}
  }
  /// Returns true if `font` has been explicitly set.
  var hasFont: Bool {_storage._font != nil}
  /// Clears the value of `font`. Subsequent reads from it will return its default value.
  mutating func clearFont() {_uniqueStorage()._font = nil}

  var fontWeight: Int32 {
    get {_storage._fontWeight ?? 0}
    set {_uniqueStorage()._fontWeight = newValue}
  }
  /// Returns true if `fontWeight` has been explicitly set.
  var hasFontWeight: Bool {_storage._fontWeight != nil}
  /// Clears the value of `fontWeight`. Subsequent reads from it will return its default value.
  mutating func clearFontWeight() {_uniqueStorage()._fontWeight = nil}

  var underlined: Int32 {
    get {_storage._underlined ?? 0}
    set {_uniqueStorage()._underlined = newValue}
  }
  /// Returns true if `underlined` has been explicitly set.
  var hasUnderlined: Bool {_storage._underlined != nil}
  /// Clears the value of `underlined`. Subsequent reads from it will return its default value.
  mutating func clearUnderlined() {_uniqueStorage()._underlined = nil}

  var strikethrough: Int32 {
    get {_storage._strikethrough ?? 0}
    set {_uniqueStorage()._strikethrough = newValue}
  }
  /// Returns true if `strikethrough` has been explicitly set.
  var hasStrikethrough: Bool {_storage._strikethrough != nil}
  /// Clears the value of `strikethrough`. Subsequent reads from it will return its default value.
  mutating func clearStrikethrough() {_uniqueStorage()._strikethrough = nil}

  var superscript: Int32 {
    get {_storage._superscript ?? 0}
    set {_uniqueStorage()._superscript = newValue}
  }
  /// Returns true if `superscript` has been explicitly set.
  var hasSuperscript: Bool {_storage._superscript != nil}
  /// Clears the value of `superscript`. Subsequent reads from it will return its default value.
  mutating func clearSuperscript() {_uniqueStorage()._superscript = nil}

  var link: String {
    get {_storage._link ?? String()}
    set {_uniqueStorage()._link = newValue}
  }
  /// Returns true if `link` has been explicitly set.
  var hasLink: Bool {_storage._link != nil}
  /// Clears the value of `link`. Subsequent reads from it will return its default value.
  mutating func clearLink() {_uniqueStorage()._link = nil}

  var color: CNColor {
    get {_storage._color ?? CNColor()}
    set {_uniqueStorage()._color = newValue}
  }
  /// Returns true if `color` has been explicitly set.
  var hasColor: Bool {_storage._color != nil}
  /// Clears the value of `color`. Subsequent reads from it will return its default value.
  mutating func clearColor() {_uniqueStorage()._color = nil}

  var attachmentInfo: CNAttachmentInfo {
    get {_storage._attachmentInfo ?? CNAttachmentInfo()}
    set {_uniqueStorage()._attachmentInfo = newValue}
  }
  /// Returns true if `attachmentInfo` has been explicitly set.
  var hasAttachmentInfo: Bool {_storage._attachmentInfo != nil}
  /// Clears the value of `attachmentInfo`. Subsequent reads from it will return its default value.
  mutating func clearAttachmentInfo() {_uniqueStorage()._attachmentInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct CNParagraphStyle: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var styleType: Int32 {
    get {_styleType ?? 0}
    set {_styleType = newValue}
  }
  /// Returns true if `styleType` has been explicitly set.
  var hasStyleType: Bool {self._styleType != nil}
  /// Clears the value of `styleType`. Subsequent reads from it will return its default value.
  mutating func clearStyleType() {self._styleType = nil}

  var alignment: Int32 {
    get {_alignment ?? 0}
    set {_alignment = newValue}
  }
  /// Returns true if `alignment` has been explicitly set.
  var hasAlignment: Bool {self._alignment != nil}
  /// Clears the value of `alignment`. Subsequent reads from it will return its default value.
  mutating func clearAlignment() {self._alignment = nil}

  var indentAmount: Int32 {
    get {_indentAmount ?? 0}
    set {_indentAmount = newValue}
  }
  /// Returns true if `indentAmount` has been explicitly set.
  var hasIndentAmount: Bool {self._indentAmount != nil}
  /// Clears the value of `indentAmount`. Subsequent reads from it will return its default value.
  mutating func clearIndentAmount() {self._indentAmount = nil}

  var checklist: CNChecklist {
    get {_checklist ?? CNChecklist()}
    set {_checklist = newValue}
  }
  /// Returns true if `checklist` has been explicitly set.
  var hasChecklist: Bool {self._checklist != nil}
  /// Clears the value of `checklist`. Subsequent reads from it will return its default value.
  mutating func clearChecklist() {self._checklist = nil}

  var listStyle: Int32 {
    get {_listStyle ?? 0}
    set {_listStyle = newValue}
  }
  /// Returns true if `listStyle` has been explicitly set.
  var hasListStyle: Bool {self._listStyle != nil}
  /// Clears the value of `listStyle`. Subsequent reads from it will return its default value.
  mutating func clearListStyle() {self._listStyle = nil}

  var blockquote: Int32 {
    get {_blockquote ?? 0}
    set {_blockquote = newValue}
  }
  /// Returns true if `blockquote` has been explicitly set.
  var hasBlockquote: Bool {self._blockquote != nil}
  /// Clears the value of `blockquote`. Subsequent reads from it will return its default value.
  mutating func clearBlockquote() {self._blockquote = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _styleType: Int32? = nil
  fileprivate var _alignment: Int32? = nil
  fileprivate var _indentAmount: Int32? = nil
  fileprivate var _checklist: CNChecklist? = nil
  fileprivate var _listStyle: Int32? = nil
  fileprivate var _blockquote: Int32? = nil
}

struct CNChecklist: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var uuid: Data {
    get {_uuid ?? Data()}
    set {_uuid = newValue}
  }
  /// Returns true if `uuid` has been explicitly set.
  var hasUuid: Bool {self._uuid != nil}
  /// Clears the value of `uuid`. Subsequent reads from it will return its default value.
  mutating func clearUuid() {self._uuid = nil}

  var done: Int32 {
    get {_done ?? 0}
    set {_done = newValue}
  }
  /// Returns true if `done` has been explicitly set.
  var hasDone: Bool {self._done != nil}
  /// Clears the value of `done`. Subsequent reads from it will return its default value.
  mutating func clearDone() {self._done = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _uuid: Data? = nil
  fileprivate var _done: Int32? = nil
}

struct CNFont: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String {
    get {_name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  var hasName: Bool {self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  mutating func clearName() {self._name = nil}

  var pointSize: Float {
    get {_pointSize ?? 0}
    set {_pointSize = newValue}
  }
  /// Returns true if `pointSize` has been explicitly set.
  var hasPointSize: Bool {self._pointSize != nil}
  /// Clears the value of `pointSize`. Subsequent reads from it will return its default value.
  mutating func clearPointSize() {self._pointSize = nil}

  var fontHints: Int32 {
    get {_fontHints ?? 0}
    set {_fontHints = newValue}
  }
  /// Returns true if `fontHints` has been explicitly set.
  var hasFontHints: Bool {self._fontHints != nil}
  /// Clears the value of `fontHints`. Subsequent reads from it will return its default value.
  mutating func clearFontHints() {self._fontHints = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _name: String? = nil
  fileprivate var _pointSize: Float? = nil
  fileprivate var _fontHints: Int32? = nil
}

struct CNColor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var red: Float {
    get {_red ?? 0}
    set {_red = newValue}
  }
  /// Returns true if `red` has been explicitly set.
  var hasRed: Bool {self._red != nil}
  /// Clears the value of `red`. Subsequent reads from it will return its default value.
  mutating func clearRed() {self._red = nil}

  var green: Float {
    get {_green ?? 0}
    set {_green = newValue}
  }
  /// Returns true if `green` has been explicitly set.
  var hasGreen: Bool {self._green != nil}
  /// Clears the value of `green`. Subsequent reads from it will return its default value.
  mutating func clearGreen() {self._green = nil}

  var blue: Float {
    get {_blue ?? 0}
    set {_blue = newValue}
  }
  /// Returns true if `blue` has been explicitly set.
  var hasBlue: Bool {self._blue != nil}
  /// Clears the value of `blue`. Subsequent reads from it will return its default value.
  mutating func clearBlue() {self._blue = nil}

  var alpha: Float {
    get {_alpha ?? 0}
    set {_alpha = newValue}
  }
  /// Returns true if `alpha` has been explicitly set.
  var hasAlpha: Bool {self._alpha != nil}
  /// Clears the value of `alpha`. Subsequent reads from it will return its default value.
  mutating func clearAlpha() {self._alpha = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _red: Float? = nil
  fileprivate var _green: Float? = nil
  fileprivate var _blue: Float? = nil
  fileprivate var _alpha: Float? = nil
}

struct CNAttachmentInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var attachmentIdentifier: String {
    get {_attachmentIdentifier ?? String()}
    set {_attachmentIdentifier = newValue}
  }
  /// Returns true if `attachmentIdentifier` has been explicitly set.
  var hasAttachmentIdentifier: Bool {self._attachmentIdentifier != nil}
  /// Clears the value of `attachmentIdentifier`. Subsequent reads from it will return its default value.
  mutating func clearAttachmentIdentifier() {self._attachmentIdentifier = nil}

  var typeUti: String {
    get {_typeUti ?? String()}
    set {_typeUti = newValue}
  }
  /// Returns true if `typeUti` has been explicitly set.
  var hasTypeUti: Bool {self._typeUti != nil}
  /// Clears the value of `typeUti`. Subsequent reads from it will return its default value.
  mutating func clearTypeUti() {self._typeUti = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _attachmentIdentifier: String? = nil
  fileprivate var _typeUti: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension CNNoteStoreProto: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "NoteStoreProto"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}document\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularMessageField(value: &self._document) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._document {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CNNoteStoreProto, rhs: CNNoteStoreProto) -> Bool {
    if lhs._document != rhs._document {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CNDocument: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Document"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}version\0\u{1}note\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._version) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._note) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._version {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._note {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CNDocument, rhs: CNDocument) -> Bool {
    if lhs._version != rhs._version {return false}
    if lhs._note != rhs._note {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CNNote: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Note"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}note_text\0\u{4}\u{3}attribute_run\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self._noteText) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.attributeRun) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._noteText {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    if !self.attributeRun.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.attributeRun, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CNNote, rhs: CNNote) -> Bool {
    if lhs._noteText != rhs._noteText {return false}
    if lhs.attributeRun != rhs.attributeRun {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CNAttributeRun: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AttributeRun"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}length\0\u{3}paragraph_style\0\u{1}font\0\u{4}\u{2}font_weight\0\u{1}underlined\0\u{1}strikethrough\0\u{1}superscript\0\u{1}link\0\u{1}color\0\u{4}\u{2}attachment_info\0")

  fileprivate class _StorageClass {
    var _length: Int32? = nil
    var _paragraphStyle: CNParagraphStyle? = nil
    var _font: CNFont? = nil
    var _fontWeight: Int32? = nil
    var _underlined: Int32? = nil
    var _strikethrough: Int32? = nil
    var _superscript: Int32? = nil
    var _link: String? = nil
    var _color: CNColor? = nil
    var _attachmentInfo: CNAttachmentInfo? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _length = source._length
      _paragraphStyle = source._paragraphStyle
      _font = source._font
      _fontWeight = source._fontWeight
      _underlined = source._underlined
      _strikethrough = source._strikethrough
      _superscript = source._superscript
      _link = source._link
      _color = source._color
      _attachmentInfo = source._attachmentInfo
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._length) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._paragraphStyle) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._font) }()
        case 5: try { try decoder.decodeSingularInt32Field(value: &_storage._fontWeight) }()
        case 6: try { try decoder.decodeSingularInt32Field(value: &_storage._underlined) }()
        case 7: try { try decoder.decodeSingularInt32Field(value: &_storage._strikethrough) }()
        case 8: try { try decoder.decodeSingularInt32Field(value: &_storage._superscript) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._link) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._color) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._attachmentInfo) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._length {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._paragraphStyle {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._font {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._fontWeight {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._underlined {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._strikethrough {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._superscript {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._link {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._color {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._attachmentInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CNAttributeRun, rhs: CNAttributeRun) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._length != rhs_storage._length {return false}
        if _storage._paragraphStyle != rhs_storage._paragraphStyle {return false}
        if _storage._font != rhs_storage._font {return false}
        if _storage._fontWeight != rhs_storage._fontWeight {return false}
        if _storage._underlined != rhs_storage._underlined {return false}
        if _storage._strikethrough != rhs_storage._strikethrough {return false}
        if _storage._superscript != rhs_storage._superscript {return false}
        if _storage._link != rhs_storage._link {return false}
        if _storage._color != rhs_storage._color {return false}
        if _storage._attachmentInfo != rhs_storage._attachmentInfo {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CNParagraphStyle: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ParagraphStyle"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}style_type\0\u{1}alignment\0\u{4}\u{2}indent_amount\0\u{1}checklist\0\u{3}list_style\0\u{2}\u{3}blockquote\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._styleType) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._alignment) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._indentAmount) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._checklist) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self._listStyle) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self._blockquote) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._styleType {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._alignment {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._indentAmount {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._checklist {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._listStyle {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._blockquote {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CNParagraphStyle, rhs: CNParagraphStyle) -> Bool {
    if lhs._styleType != rhs._styleType {return false}
    if lhs._alignment != rhs._alignment {return false}
    if lhs._indentAmount != rhs._indentAmount {return false}
    if lhs._checklist != rhs._checklist {return false}
    if lhs._listStyle != rhs._listStyle {return false}
    if lhs._blockquote != rhs._blockquote {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CNChecklist: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Checklist"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uuid\0\u{1}done\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._uuid) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._done) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._uuid {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._done {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CNChecklist, rhs: CNChecklist) -> Bool {
    if lhs._uuid != rhs._uuid {return false}
    if lhs._done != rhs._done {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CNFont: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Font"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}point_size\0\u{3}font_hints\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self._pointSize) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._fontHints) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._pointSize {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._fontHints {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CNFont, rhs: CNFont) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._pointSize != rhs._pointSize {return false}
    if lhs._fontHints != rhs._fontHints {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CNColor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Color"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}red\0\u{1}green\0\u{1}blue\0\u{1}alpha\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self._red) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self._green) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self._blue) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self._alpha) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._red {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._green {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._blue {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._alpha {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CNColor, rhs: CNColor) -> Bool {
    if lhs._red != rhs._red {return false}
    if lhs._green != rhs._green {return false}
    if lhs._blue != rhs._blue {return false}
    if lhs._alpha != rhs._alpha {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CNAttachmentInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "AttachmentInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}attachment_identifier\0\u{3}type_uti\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._attachmentIdentifier) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._typeUti) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._attachmentIdentifier {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._typeUti {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CNAttachmentInfo, rhs: CNAttachmentInfo) -> Bool {
    if lhs._attachmentIdentifier != rhs._attachmentIdentifier {return false}
    if lhs._typeUti != rhs._typeUti {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
